# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_core.ipynb",
         "test_if_card_has_higher_value": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Pascal.github.io/durak/"

git_url = "https://github.com/Pascal/durak/tree/master/"

def custom_doc_links(name): return None
