# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['Card', 'test_if_card_has_higher_value', 'test_if_card_has_same_value', 'test_if_color_matches']

# Cell
import functools
import random

# Cell
@functools.total_ordering
class Card():
    def __init__(self, value, color):
        self.value = value
        self.color = color
        self.is_trump = False

    def make_trump(self):
        "Makes a card to a trump card at the beginning of a round."
        self.is_trump = True

    def _matches_color(self,other):
        return self.color == other.color

    def __eq__(self, other):
        if not isinstance(other, Card):
            raise NotImplementedError
        return self.value == other.value

    def __gt__(self, other):
        if not isinstance(other, Card):
            raise NotImplementedError
        return self.value >= other.value

    def __repr__(self):
        return f'Card({self.value}, {self.color}, trump={self.is_trump})'


# Cell
def test_if_card_has_higher_value():
    heart_seven = Card(7, 'heart')
    heart_six = Card(6, 'heart')
    assert heart_seven > heart_six

def test_if_card_has_same_value():
    heart_seven = Card(7, 'heart')
    spade_seven = Card(7, 'spade')
    assert heart_seven == spade_seven

def test_if_color_matches():
    heart_seven = Card(7, 'heart')
    heart_six = Card(6, 'heart')
    assert heart_seven._matches_color(heart_six)