# AUTOGENERATED! DO NOT EDIT! File to edit: 01_Game.ipynb (unless otherwise specified).

__all__ = ['game_setup']

# Cell
import random
from .core import (
                       Player,
                       gen_card_deck,
                       deal_starting_hand,
                       draw_trump_card,
                       make_trumps,
                       determine_starting_player
                       )

# Cell
def game_setup():
    player_names = ['Carlos', 'Mike', 'Andreas', 'Pascal']
    players = [Player(name) for name in player_names]
    cards = gen_card_deck()
    deal_starting_hand(players, cards)
    trump = draw_trump_card(cards)
    make_trumps(players, trump)
    determine_starting_player(players)
